spring.application.name=backend

spring.profiles.active=dev

spring.datasource.url=jdbc:${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_USERNAME:}

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=never

server.port=${PORT:8080}
server.address=0.0.0.0

spring.sql.init.encoding=UTF-8
spring.jpa.properties.hibernate.connection.CharSet=utf8

#app.cors.allowed-origins=https://kakeibo-app-gamma-two.vercel.app